### ISSUE TITLE
Step 4: Make marble solid (collisions 1 of 3)

### ISSUE THREAD

**Issue by lokijoanderso** [computers-for-learning-20/Lab4_IntroToUnity#12]
Step 4: Enable Collisions

If you’ve successfully completed the last part, you will notice that the marble will phase right through things. Cool, but not super useful. Unity has some built in components that will allow us to run into stuff, and not just through it. In fact, these components will allow us to even apply real world physics (and some irreal physics) to collisions between objects.
Note that this is explained well in the book, so make sure to read the book for how to do this.

In this section you will:

- Make the Marble a solid object by adding a RigidBody component using the Unity GUI.
    Hint: If you see strange behavior, try messing with the mass, drag, or gravity on this RigidBody

- Add a Collider component to the Marble using the Unity GUI.

- Update the GoalBehavior script (which controls the behavior of all the goals) so that the goals disappear upon contact with the marble
    HINT: If you are perplexed on how to do this, check the textbook.

**Comment by jramtos** [comment]
Done: but not sure if all goals should disappear after marble touches one goal or just one goal disappears.

**Comment by lokijoanderso** [comment]
I made it so just the one touched disappears.
I'm pretty sure that's the way it should work...
We can talk about this.

**Comment by jramtos** [comment]
Yes. I didn't push my changes and then I saw you already had done it haha 
I'm too slow. But yes, I did the same implementation.
