### ISSUE TITLE
Extra Credit: document any extra credit in ReadMe file

### ISSUE THREAD

**Issue by lokijoanderso** [computers-for-learning-20/Lab4_IntroToUnity#17]
Once you have completed the above, you can move on to extra credit if you so choose. For extra credit you can add these elements covered in the textbook chapters 6 and 7, but not in this lab:

- Add some particles to any object or prefab
   Maybe even try to trigger them with a collision??
- Add animation to any object
- Any other element from those chapters, upon approval from instructional staff.

Note: If you choose to add extra credit, add a README.txt in your root directory so we know what you added!
Another Note: No matter what you choose, you get up to 5 points extra credit. The lab is worth 50 total points. Focus on this last (if at all).

**Comment by lokijoanderso** [comment]
Added a note about the particles to ReadMe.
If we do more, we can add that too.

**Comment by jramtos** [comment]
Completed
